Added ability to select between different SPH smoothing kernels
pynbody/pynbody pull request #648
Opened 2022-02-01 12:42 UTC by j-davies-astro

I've added an extra option to the sph routines that allows the user to pick a different kernel for making images. New kernels need to be defined as functions in the Kernel() class, and so far I've only added 'spline' (the current pynbody default) and 'wendlandC2', which is the kernel EAGLE uses. If no kernel is specified, 'spline' is used.

2022-02-01 12:47 UTC, apontzen requested changes
Nice to do this but the change in the construction of Kernels will break some other projects. The Wendland kernel should be implemented as a new subclass i.e.

```python
class WendlendKernel(Kernel):
    def get_value(...):
        ....
```

That is the basic point, some detailed comments inline

2022-02-01 12:47 UTC, apontzen commented on pynbody/sph/__init__.py
> +        elif self.type == 'wendlandC2':
This should be implemented as a subclass, not as a string option

2022-02-01 12:47 UTC, apontzen commented on pynbody/sph/__init__.py
> +    def __init__(self, type='spline'):
The parameter passed here should indeed be a `Kernel` object, and an appropriate subclass can then be passed if one wants to use a Wendland kernel

2022-02-01 12:47 UTC, apontzen commented on pynbody/plot/sph.py
> +    kernel = sph.Kernel(type=kernel_type)
Here you can create the appropraite kernel object based on the string passed in (i.e. it's ok for the user-facing bit to have strings)

2022-02-01 12:47 UTC, apontzen commented on pynbody/plot/sph.py
> +        kernel = sph.Kernel2D(type=kernel_type)
This line should read `kernel = sph.Kernel2D(kernel)`, to construct a 2D kernel over whatever kernel has been previously selected

2022-02-01 12:47 UTC, apontzen commented on pynbody/plot/sph.py
> +            kernel = sph.Kernel2D(type=kernel_type)
see comment above

2022-02-01 12:47 UTC, apontzen commented on pynbody/sph/__init__.py
> +    def __init__(self,type='spline'):
This option should not be present, rather a subclass should be implemented for a different kernel type

2022-02-01 16:36 UTC, j-davies-astro commented
Thanks for the feedback, I think the implementation should be correct now. Happy to change the way it's handled if the user requests an invalid kernel - right now it defaults back to spline with a printed warning but if you'd like to put something more fancy in I can make further changes.

2022-02-01 16:37 UTC, apontzen reviewed
Almost there!

2022-02-01 16:37 UTC, apontzen commented on pynbody/plot/sph.py
> +        print('Invalid kernel_type specified (options are "spline" and "wendlandC2"). Defaulting to a cubic spline...')
This should be `raise ValueError` not `print`

2022-02-01 16:37 UTC, apontzen commented on pynbody/plot/sph.py
> +    *kernel_type* ('spline'): SPH kernel to use for smoothing. Defualts to a
typo (Def*ua*lts)

2022-02-01 16:41 UTC, j-davies-astro commented on pynbody/plot/sph.py
> +    *kernel_type* ('spline'): SPH kernel to use for smoothing. Defualts to a
whoops!

2022-02-01 16:45 UTC, apontzen commented
Sorry one last thing - I think it's worth checking this actually works (and continues to work) with a test. Under `sph_image_test` you will find a `test_images` function which you could easily adapt to also check asking for the alternative kernel behaves as expected (ie. presumably it should return a different image)

2022-02-01 18:33 UTC, apontzen commented
Sorry I meant the latter - check the image is not only different but also correct. Ie just add one more reference numpy file to test against.

2022-02-03 15:46 UTC, apontzen approved these changes

2022-02-03 15:46 UTC, merged